# gen_lesson5.py
# WPS-Z80 Assembler Script - Lesson 5: Branching
# Generates lesson5.bin (raw binary) and lesson5.asm (annotated listing).
#
# Program Logic:
#   1. Counted loop: B counts down from 3 to 0 using DEC B / JR NZ.
#   2. Conditional store: CP tests A == 0xFF, then JP Z branches to MATCH.
#   3. At MATCH: LD (0x8000), A stores the sentinel value as proof.
#   4. HALT.
#
# Address map (hand-assembled, verified below):
#   0x0000  LD B, 03          [06 03]
#   0x0002  DEC B    (LOOP)   [05]
#   0x0003  JR NZ, LOOP       [20 FE]   offset = -2 (PC after fetch = 0x0005; 0x0005 + (-2) = 0x0003... wait)
#   0x0005  LD A, FF          [3E FF]
#   0x0007  CP FF             [FE FF]
#   0x0009  JP Z, 0x000F      [CA 0F 00]
#   0x000C  LD A, 00          [3E 00]   (not-taken / wrong-branch trap path)
#   0x000E  HALT              [76]      (trap)
#   0x000F  LD (0x8000), A    [32 00 80] (MATCH)
#   0x0012  HALT              [76]

# ---------------------------------------------------------------------------
# Displacement calculation for JR NZ, LOOP:
#   After fetching opcode 0x20 at 0x0003, PC = 0x0004.
#   After fetching displacement byte at 0x0004, PC = 0x0005.
#   We want to jump to LOOP = 0x0002.
#   offset = 0x0002 - 0x0005 = -3  =>  two's complement byte: 256 - 3 = 0xFD
# ---------------------------------------------------------------------------

LOOP_TARGET = 0x0002   # address of DEC B

# Build the binary as a list of (bytes, asm_string) pairs for co-generation.
instructions = [
    # (raw bytes,              asm label,  mnemonic string)
    ([0x06, 0x03],            "",         "LD B, 0x03"),
    ([0x05],                  "LOOP:",    "DEC B"),
    ([0x20, 0xFD],            "",         "JR NZ, LOOP        ; offset=0xFD (-3): PC after fetch=0x0005, target=0x0002"),
    ([0x3E, 0xFF],            "",         "LD A, 0xFF"),
    ([0xFE, 0xFF],            "",         "CP 0xFF            ; Z set if A==0xFF"),
    ([0xCA, 0x0F, 0x00],      "",         "JP Z, 0x000F       ; jump to MATCH if Z=1"),
    ([0x3E, 0x00],            "",         "LD A, 0x00         ; [NOT TAKEN] wrong-branch trap"),
    ([0x76],                  "",         "HALT               ; [NOT TAKEN] trap halt"),
    ([0x32, 0x00, 0x80],      "MATCH:",   "LD (0x8000), A     ; store A=0xFF as proof of correct branch"),
    ([0x76],                  "",         "HALT"),
]

# ---------------------------------------------------------------------------
# Generate binary
# ---------------------------------------------------------------------------
binary = bytearray()
for (raw, label, mnemonic) in instructions:
    binary += bytes(raw)

bin_path = "programs/lesson5.bin"
with open(bin_path, "wb") as f:
    f.write(binary)

# ---------------------------------------------------------------------------
# Generate annotated .asm listing (address | hex bytes | label | mnemonic)
# ---------------------------------------------------------------------------
asm_lines = [
    "; lesson5.asm  --  AUTO-GENERATED by gen_lesson5.py  --  DO NOT EDIT BY HAND",
    "; WPS-Z80 Lesson 5: Branching (JR NZ counted loop + JP Z conditional store)",
    "; ORG 0x0000",
    "",
]

addr = 0
for (raw, label, mnemonic) in instructions:
    hex_bytes = " ".join(f"{b:02X}" for b in raw)
    label_col = f"{label:<8}"          # fixed-width label column
    addr_col  = f"0x{addr:04X}"
    hex_col   = f"{hex_bytes:<12}"     # fixed-width hex column (max 3 bytes = "XX XX XX  ")
    asm_lines.append(f"  {addr_col}  {hex_col}  {label_col}  {mnemonic}")
    addr += len(raw)

asm_path = "programs/lesson5.asm"
with open(asm_path, "w") as f:
    f.write("\n".join(asm_lines) + "\n")

# ---------------------------------------------------------------------------
# Console summary
# ---------------------------------------------------------------------------
print(f"Generated: {bin_path}  ({len(binary)} bytes)")
print(f"Generated: {asm_path}")
print()
print("Expected execution trace:")
print("  LD B, 03          ; B=3")
print("  DEC B  x3         ; B=2 (Z:0), B=1 (Z:0), B=0 (Z:1)")
print("  JR NZ  x3         ; taken x2, not taken on third (Z=1)")
print("  LD A, FF          ; A=0xFF")
print("  CP FF             ; Z=1 (match), C=0")
print("  JP Z, 000F        ; taken -> MATCH")
print("  LD (8000), A      ; RAM[0x8000] = 0xFF")
print("  HALT")