# gen_lesson7.py
# WPS-Z80 Assembler Script - Lesson 7: Full Register Set + LDIR
# Generates lesson7.bin and lesson7.asm
#
# Program: Fill entire VRAM with a 16-colour stripe pattern using LDIR.
# Each of the 16 pens fills 200/16 = 12 or 13 rows (200 rows total).
# Uses Mode 0 encoding: 1 byte = 2 pixels, solid pen byte formula below.
#
# Mode 0 solid pen byte encoding:
#   pen value is 4 bits: p[3] p[2] p[1] p[0]
#   byte = p[0]<<7 | p[0]<<6... wait, let's derive carefully:
#
#   bit7=p0[0] bit5=p0[2] bit3=p0[1] bit1=p0[3]  (pixel 0)
#   bit6=p1[0] bit4=p1[2] bit2=p1[1] bit0=p1[3]  (pixel 1)
#
#   For solid colour (both pixels = pen n):
#   bit7 = n[0], bit6 = n[0]
#   bit5 = n[2], bit4 = n[2]
#   bit3 = n[1], bit2 = n[1]
#   bit1 = n[3], bit0 = n[3]
#
# Strategy:
#   1. Build a 16000-byte fill table in program memory (at 0x0100)
#      Each byte corresponds to one VRAM byte at the matching CRTC offset.
#      We fill it with the correct solid-colour byte for each screen row's pen.
#   2. LD HL, 0x0100   ; source = fill table
#      LD DE, 0xC000   ; destination = VRAM
#      LD BC, 0x3E80   ; count = 16000
#      LDIR            ; copy entire table to VRAM in one instruction
#      HALT

def solid_mode0_byte(pen):
    """
    Return the Mode 0 byte encoding two pixels both with colour 'pen'.
    pen is 0-15 (4 bits: p3 p2 p1 p0).
    """
    p = [( pen >> i) & 1 for i in range(4)]  # p[0]=LSB, p[3]=MSB
    byte = (p[0] << 7) | (p[0] << 6) | \
           (p[2] << 5) | (p[2] << 4) | \
           (p[1] << 3) | (p[1] << 2) | \
           (p[3] << 1) | (p[3] << 0)
    return byte

def crtc_offset(y, x):
    """CRTC address offset from 0xC000 for pixel row y, byte column x."""
    return (y % 8) * 0x0800 + (y // 8) * 0x0050 + x

# ---------------------------------------------------------------------------
# Build fill table: 16384 bytes, indexed by CRTC offset
# Row y gets pen = y * 16 // 200  (evenly divides 200 rows into 16 bands)
# ---------------------------------------------------------------------------
fill_table = bytearray(16384)
for y in range(200):
    pen = (y * 16) // 200      # pen 0 = rows 0-11, pen 1 = 12-23, ... pen 15 = 187-199
    fill_byte = solid_mode0_byte(pen)
    for x in range(80):        # 80 bytes per row in Mode 0
        offset = crtc_offset(y, x)
        if offset < 16384:
            fill_table[offset] = fill_byte

# ---------------------------------------------------------------------------
# Assemble program
# Layout:
#   0x0000: LD HL, 0x0100   [21 00 01]
#   0x0003: LD DE, 0xC000   [11 00 C0]
#   0x0006: LD BC, 0x4000   [01 00 40]
#   0x0009: LDIR            [ED B0]
#   0x000B: HALT            [76]
#   0x0100: fill_table      [16384 bytes]
# ---------------------------------------------------------------------------

FILL_TABLE_ADDR = 0x0100

program = bytearray(FILL_TABLE_ADDR + len(fill_table))

# LD HL, FILL_TABLE_ADDR
program[0x0000] = 0x21
program[0x0001] = FILL_TABLE_ADDR & 0xFF
program[0x0002] = (FILL_TABLE_ADDR >> 8) & 0xFF

# LD DE, 0xC000
program[0x0003] = 0x11
program[0x0004] = 0x00
program[0x0005] = 0xC0

# LD BC, 0x4000  (16384 bytes = full VRAM)
program[0x0006] = 0x01
program[0x0007] = 0x00
program[0x0008] = 0x40

# LDIR
program[0x0009] = 0xED
program[0x000A] = 0xB0

# HALT
program[0x000B] = 0x76

# Fill table
program[FILL_TABLE_ADDR:FILL_TABLE_ADDR + len(fill_table)] = fill_table

# ---------------------------------------------------------------------------
# Write binary
# ---------------------------------------------------------------------------
bin_path = "programs/lesson7.bin"
with open(bin_path, "wb") as f:
    f.write(program)

# ---------------------------------------------------------------------------
# Write .asm listing
# ---------------------------------------------------------------------------
asm_lines = [
    "; lesson7.asm  --  AUTO-GENERATED by gen_lesson7.py  --  DO NOT EDIT",
    "; WPS-Z80 Lesson 7: Full Register Set + LDIR",
    "; Fills entire VRAM (16000 bytes) with 16-colour Mode 0 stripe pattern.",
    "; Uses LDIR to copy a pre-built fill table from program memory to VRAM.",
    ";",
    "; Mode 0 palette (default firmware):",
]
for i in range(16):
    b = solid_mode0_byte(i)
    asm_lines.append(f";   pen {i:2d} fill byte = 0x{b:02X}  ({b:08b})")
asm_lines += [
    ";",
    "; ORG 0x0000",
    "",
    f"  0x0000  21 00 01          LD HL, 0x{FILL_TABLE_ADDR:04X}  ; source: fill table",
    "  0x0003  11 00 C0          LD DE, 0xC000   ; destination: VRAM base",
    "  0x0006  01 00 40          LD BC, 0x4000   ; count: 16384 bytes (full VRAM)",
    "  0x0009  ED B0             LDIR            ; block copy HL->DE, BC times",
    "  0x000B  76                HALT",
    "",
    f"  0x{FILL_TABLE_ADDR:04X}  [16000 bytes]     fill_table  ; pre-computed VRAM data",
]

asm_path = "programs/lesson7.asm"
with open(asm_path, "w") as f:
    f.write("\n".join(asm_lines) + "\n")

# ---------------------------------------------------------------------------
# Console summary
# ---------------------------------------------------------------------------
print(f"Generated: {bin_path}  ({len(program)} bytes)")
print(f"Generated: {asm_path}")
print()
print("Mode 0 solid pen fill bytes:")
for i in range(16):
    b = solid_mode0_byte(i)
    print(f"  pen {i:2d}: 0x{b:02X}  ({b:08b})")
print()
print("To run:")
print("  g++ main.cpp -o emulator.exe -std=c++17")
print("  g++ monitor.cpp -o monitor.exe -I SDL3/include -L SDL3/lib -lSDL3 -std=c++17")
print("  python programs/gen_lesson7.py")
print("  .\\monitor.exe programs\\lesson7_vram --mode 0   (terminal 1)")
print("  .\\emulator.exe programs\\lesson7.bin             (terminal 2)")
print()
print("Expected: full 320x200 window filled with 16 horizontal colour bands.")