; lesson7.asm  --  AUTO-GENERATED by gen_lesson7.py  --  DO NOT EDIT
; WPS-Z80 Lesson 7: Full Register Set + LDIR
; Fills entire VRAM (16000 bytes) with 16-colour Mode 0 stripe pattern.
; Uses LDIR to copy a pre-built fill table from program memory to VRAM.
;
; Mode 0 palette (default firmware):
;   pen  0 fill byte = 0x00  (00000000)
;   pen  1 fill byte = 0xC0  (11000000)
;   pen  2 fill byte = 0x0C  (00001100)
;   pen  3 fill byte = 0xCC  (11001100)
;   pen  4 fill byte = 0x30  (00110000)
;   pen  5 fill byte = 0xF0  (11110000)
;   pen  6 fill byte = 0x3C  (00111100)
;   pen  7 fill byte = 0xFC  (11111100)
;   pen  8 fill byte = 0x03  (00000011)
;   pen  9 fill byte = 0xC3  (11000011)
;   pen 10 fill byte = 0x0F  (00001111)
;   pen 11 fill byte = 0xCF  (11001111)
;   pen 12 fill byte = 0x33  (00110011)
;   pen 13 fill byte = 0xF3  (11110011)
;   pen 14 fill byte = 0x3F  (00111111)
;   pen 15 fill byte = 0xFF  (11111111)
;
; ORG 0x0000

  0x0000  21 00 01          LD HL, 0x0100  ; source: fill table
  0x0003  11 00 C0          LD DE, 0xC000   ; destination: VRAM base
  0x0006  01 00 40          LD BC, 0x4000   ; count: 16384 bytes (full VRAM)
  0x0009  ED B0             LDIR            ; block copy HL->DE, BC times
  0x000B  76                HALT

  0x0100  [16000 bytes]     fill_table  ; pre-computed VRAM data
