; lesson8.asm  --  AUTO-GENERATED by gen_lesson8.py  --  DO NOT EDIT
; WPS-Z80 Lesson 8: Full ALU
; Draws a filled rectangle using runtime address arithmetic.
;
; Background: pen 9 (green)    fill byte = 0xC3
; Rectangle:  pen 6 (bright red) fill byte = 0x3C
; Rectangle:  rows 60-139, byte columns 20-59
;             = pixel columns 40-119 in Mode 0
;
; ORG 0x0000
  0x0000  C3 00 42          JP 0x4200     ; jump to code
  0x0100  [16384 bytes]     fill_table  ; background fill (pen 9)
  0x4100  [160 bytes]       addr_table  ; CRTC row addresses for rectangle

; CODE at 0x4200
  0x4200  21 00 01          LD HL, 0x0100  ; phase 1: fill background
  ...     11 00 C0          LD DE, 0xC000
  ...     01 00 40          LD BC, 0x4000
  ...     ED B0             LDIR

  ...     21 00 41          LD HL, 0x4100  ; phase 2: draw rectangle
  ...     06 50              LD B, 80         ; row counter
;
; ROW_LOOP:
  ...     5E                LD E, (HL)      ; low byte of row CRTC address
  ...     23                INC HL
  ...     56                LD D, (HL)      ; high byte of row CRTC address
  ...     23                INC HL
  ...     3E 3C              LD A, 0x3C       ; pen 6 fill byte
  ...     0E 28              LD C, 40          ; bytes per row
;
; FILL_LOOP:
  ...     12                LD (DE), A      ; write pixel byte
  ...     13                INC DE          ; advance VRAM pointer
  ...     0D                DEC C           ; decrement byte counter
  ...     20 FA             JR NZ, FILL_LOOP
  ...     05                DEC B           ; decrement row counter
  ...     20 F2             JR NZ, ROW_LOOP
  ...     76                HALT
