; lesson9.asm  --  AUTO-GENERATED by gen_lesson9.py  --  DO NOT EDIT
; WPS-Z80 Lesson 9: Sprite Blitting with AND mask transparency
;
; Background: pen 1 (dark blue)       fill byte 0xC0
; Ground:     pen 12 (yellow-brown) at y=148
; Alligator:  24x16 px, facing left,  byte col 34 (px 68), row 132
; Hero:       16x20 px, facing right, byte col 8 (px 16), row 128
;
; Masked blit per byte pair:
;   LD B,(HL) / INC HL   B = AND mask
;   LD A,(HL) / INC HL   A = sprite byte
;   PUSH HL               save table pointer
;   LD L, A               move sprite to L
;   LD A,(DE)             read background from VRAM
;   AND B                 clear opaque pixel positions
;   OR L                  write sprite pixels
;   LD (DE),A             write back to VRAM
;   POP HL                restore table pointer
;   INC DE / DEC C / JR NZ
