; lesson5.asm  --  AUTO-GENERATED by gen_lesson5.py  --  DO NOT EDIT BY HAND
; WPS-Z80 Lesson 5: Branching (JR NZ counted loop + JP Z conditional store)
; ORG 0x0000

  0x0000  06 03                   LD B, 0x03
  0x0002  05            LOOP:     DEC B
  0x0003  20 FD                   JR NZ, LOOP        ; offset=0xFD (-3): PC after fetch=0x0005, target=0x0002
  0x0005  3E FF                   LD A, 0xFF
  0x0007  FE FF                   CP 0xFF            ; Z set if A==0xFF
  0x0009  CA 0F 00                JP Z, 0x000F       ; jump to MATCH if Z=1
  0x000C  3E 00                   LD A, 0x00         ; [NOT TAKEN] wrong-branch trap
  0x000E  76                      HALT               ; [NOT TAKEN] trap halt
  0x000F  32 00 80      MATCH:    LD (0x8000), A     ; store A=0xFF as proof of correct branch
  0x0012  76                      HALT
