; lesson10.asm  --  AUTO-GENERATED by gen_lesson10.py  --  DO NOT EDIT
; WPS-Z80 Lesson 10: Movement — sprite erase/redraw loop, 48 VRAM frames
;
; Alligator: 24x16 px, facing left, starts byte col 60, moves left
; Hero:      16x20 px, facing right, starts byte col 8, moves right
; Frames:    48
;
; New opcodes: DJNZ (0x10), OUT (n),A (0xD3)
;
; Blit strategy:
;   Row-address tables hold base VRAM addresses (x=0) per sprite row.
;   X byte-column is stored in RAM and added to each base address at runtime.
;   Sprite data tables hold (mask, spr_byte) pairs — no addresses embedded.
;   PUSH HL / POP HL preserves the row-addr table pointer across inner loops.
;   Sprite data pointer lives in RAM (SPR_PTR_LO/HI) across rows.
;
; RAM: alig_x=0x8000  hero_x=0x8001  frame_ctr=0x8002  spr_ptr=0x8003/0x8004
  ; LD SP, 0xF000  ; initialise stack

  ; === Initial VRAM fill ===

  ; === Draw ground (once) ===

  ; === Frame loop: 48 frames ===
  .frame_loop:  ; 0x4752

  ; === erase_alig (erase) ===
  ; LD HL, 0x4000  ; row-addr table
  ; LD B, 16  ; row counter
  .row_erase_alig:
  ; LD E, (HL)
  ; INC HL
  ; LD D, (HL)
  ; INC HL
  ; PUSH HL  ; save row-addr table ptr
  ; LD A, (x_col)
  ; ADD A, E
  ; LD E, A
  ; JR NC, +1  ; skip INC D if no carry
  ; INC D
  ; LD C, 12
  ; LD A, 0xC0  ; background byte
    .ebyte_erase_alig:
  ; LD (DE), A
  ; INC DE
  ; DEC C
  ; JR NZ, .ebyte
  ; POP HL  ; restore row-addr table ptr
  ; DJNZ .row

  ; === erase_hero (erase) ===
  ; LD HL, 0x4020  ; row-addr table
  ; LD B, 20  ; row counter
  .row_erase_hero:
  ; LD E, (HL)
  ; INC HL
  ; LD D, (HL)
  ; INC HL
  ; PUSH HL  ; save row-addr table ptr
  ; LD A, (x_col)
  ; ADD A, E
  ; LD E, A
  ; JR NC, +1  ; skip INC D if no carry
  ; INC D
  ; LD C, 8
  ; LD A, 0xC0  ; background byte
    .ebyte_erase_hero:
  ; LD (DE), A
  ; INC DE
  ; DEC C
  ; JR NZ, .ebyte
  ; POP HL  ; restore row-addr table ptr
  ; DJNZ .row

  ; --- update alig_x ---

  ; --- update hero_x ---

  ; --- select animation frame ---

  ; --- alig frame A ---

  ; === blit_alig_A (blit) ===
  ; LD A, 0x50  ; init sprite ptr lo
  ; LD (SPR_PTR_LO), A
  ; LD A, 0x40  ; init sprite ptr hi
  ; LD (SPR_PTR_HI), A
  ; LD HL, 0x4000  ; row-addr table
  ; LD B, 16  ; row counter
  .row_blit_alig_A:
  ; LD E, (HL)
  ; INC HL
  ; LD D, (HL)
  ; INC HL
  ; PUSH HL  ; save row-addr table ptr
  ; LD A, (x_col)
  ; ADD A, E
  ; LD E, A
  ; JR NC, +1  ; skip INC D if no carry
  ; INC D
  ; LD C, 12
  ; LD A, (SPR_PTR_LO)
  ; LD L, A
  ; LD A, (SPR_PTR_HI)
  ; LD H, A
  ; LD A, B  ; save row counter
  ; LD (ROW_CTR_SAVE), A
    .bbyte_blit_alig_A:
  ; LD B, (HL)   ; mask byte
  ; INC HL
  ; LD A, (HL)   ; sprite byte
  ; INC HL
  ; PUSH HL      ; save sprite data ptr
  ; LD L, A      ; move sprite byte to L
  ; LD A, (DE)   ; read VRAM background
  ; AND B        ; clear opaque pixels
  ; OR  L        ; write sprite pixels
  ; LD (DE), A   ; write back to VRAM
  ; POP HL       ; restore sprite data ptr
  ; INC DE
  ; DEC C
  ; JR NZ, .bbyte
  ; LD A, L
  ; LD (SPR_PTR_LO), A
  ; LD A, H
  ; LD (SPR_PTR_HI), A
  ; LD A, (ROW_CTR_SAVE)  ; restore row counter
  ; LD B, A
  ; POP HL  ; restore row-addr table ptr
  ; DJNZ .row

  ; --- alig frame B ---

  ; === blit_alig_B (blit) ===
  ; LD A, 0xD0  ; init sprite ptr lo
  ; LD (SPR_PTR_LO), A
  ; LD A, 0x41  ; init sprite ptr hi
  ; LD (SPR_PTR_HI), A
  ; LD HL, 0x4000  ; row-addr table
  ; LD B, 16  ; row counter
  .row_blit_alig_B:
  ; LD E, (HL)
  ; INC HL
  ; LD D, (HL)
  ; INC HL
  ; PUSH HL  ; save row-addr table ptr
  ; LD A, (x_col)
  ; ADD A, E
  ; LD E, A
  ; JR NC, +1  ; skip INC D if no carry
  ; INC D
  ; LD C, 12
  ; LD A, (SPR_PTR_LO)
  ; LD L, A
  ; LD A, (SPR_PTR_HI)
  ; LD H, A
  ; LD A, B  ; save row counter
  ; LD (ROW_CTR_SAVE), A
    .bbyte_blit_alig_B:
  ; LD B, (HL)   ; mask byte
  ; INC HL
  ; LD A, (HL)   ; sprite byte
  ; INC HL
  ; PUSH HL      ; save sprite data ptr
  ; LD L, A      ; move sprite byte to L
  ; LD A, (DE)   ; read VRAM background
  ; AND B        ; clear opaque pixels
  ; OR  L        ; write sprite pixels
  ; LD (DE), A   ; write back to VRAM
  ; POP HL       ; restore sprite data ptr
  ; INC DE
  ; DEC C
  ; JR NZ, .bbyte
  ; LD A, L
  ; LD (SPR_PTR_LO), A
  ; LD A, H
  ; LD (SPR_PTR_HI), A
  ; LD A, (ROW_CTR_SAVE)  ; restore row counter
  ; LD B, A
  ; POP HL  ; restore row-addr table ptr
  ; DJNZ .row

  ; --- hero frame A ---

  ; === blit_hero_A (blit) ===
  ; LD A, 0x50  ; init sprite ptr lo
  ; LD (SPR_PTR_LO), A
  ; LD A, 0x43  ; init sprite ptr hi
  ; LD (SPR_PTR_HI), A
  ; LD HL, 0x4020  ; row-addr table
  ; LD B, 20  ; row counter
  .row_blit_hero_A:
  ; LD E, (HL)
  ; INC HL
  ; LD D, (HL)
  ; INC HL
  ; PUSH HL  ; save row-addr table ptr
  ; LD A, (x_col)
  ; ADD A, E
  ; LD E, A
  ; JR NC, +1  ; skip INC D if no carry
  ; INC D
  ; LD C, 8
  ; LD A, (SPR_PTR_LO)
  ; LD L, A
  ; LD A, (SPR_PTR_HI)
  ; LD H, A
  ; LD A, B  ; save row counter
  ; LD (ROW_CTR_SAVE), A
    .bbyte_blit_hero_A:
  ; LD B, (HL)   ; mask byte
  ; INC HL
  ; LD A, (HL)   ; sprite byte
  ; INC HL
  ; PUSH HL      ; save sprite data ptr
  ; LD L, A      ; move sprite byte to L
  ; LD A, (DE)   ; read VRAM background
  ; AND B        ; clear opaque pixels
  ; OR  L        ; write sprite pixels
  ; LD (DE), A   ; write back to VRAM
  ; POP HL       ; restore sprite data ptr
  ; INC DE
  ; DEC C
  ; JR NZ, .bbyte
  ; LD A, L
  ; LD (SPR_PTR_LO), A
  ; LD A, H
  ; LD (SPR_PTR_HI), A
  ; LD A, (ROW_CTR_SAVE)  ; restore row counter
  ; LD B, A
  ; POP HL  ; restore row-addr table ptr
  ; DJNZ .row

  ; --- hero frame B ---

  ; === blit_hero_B (blit) ===
  ; LD A, 0x90  ; init sprite ptr lo
  ; LD (SPR_PTR_LO), A
  ; LD A, 0x44  ; init sprite ptr hi
  ; LD (SPR_PTR_HI), A
  ; LD HL, 0x4020  ; row-addr table
  ; LD B, 20  ; row counter
  .row_blit_hero_B:
  ; LD E, (HL)
  ; INC HL
  ; LD D, (HL)
  ; INC HL
  ; PUSH HL  ; save row-addr table ptr
  ; LD A, (x_col)
  ; ADD A, E
  ; LD E, A
  ; JR NC, +1  ; skip INC D if no carry
  ; INC D
  ; LD C, 8
  ; LD A, (SPR_PTR_LO)
  ; LD L, A
  ; LD A, (SPR_PTR_HI)
  ; LD H, A
  ; LD A, B  ; save row counter
  ; LD (ROW_CTR_SAVE), A
    .bbyte_blit_hero_B:
  ; LD B, (HL)   ; mask byte
  ; INC HL
  ; LD A, (HL)   ; sprite byte
  ; INC HL
  ; PUSH HL      ; save sprite data ptr
  ; LD L, A      ; move sprite byte to L
  ; LD A, (DE)   ; read VRAM background
  ; AND B        ; clear opaque pixels
  ; OR  L        ; write sprite pixels
  ; LD (DE), A   ; write back to VRAM
  ; POP HL       ; restore sprite data ptr
  ; INC DE
  ; DEC C
  ; JR NZ, .bbyte
  ; LD A, L
  ; LD (SPR_PTR_LO), A
  ; LD A, H
  ; LD (SPR_PTR_HI), A
  ; LD A, (ROW_CTR_SAVE)  ; restore row counter
  ; LD B, A
  ; POP HL  ; restore row-addr table ptr
  ; DJNZ .row

  ; --- increment frame_ctr (mod 8) ---

  ; --- frame sync: dump VRAM ---
  ; DEC B
  ; JP NZ, .frame_loop  (patched)
  ; HALT
